name: Playwright Table Sum

on:
  push:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright Browsers 24f3002267@ds.study.iitm.ac.in
        run: npx playwright install --with-deps

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scrape.js
